APPLICATION = driver_ezo_ph
include ../Makefile.tests_common

# If no BOARD is found in the environment, use this default:
BOARD = pba-d-01-kw2x

# Modules to include:
USEMODULE += ezo_ph
USEMODULE += xtimer
USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ps

include $(RIOTBASE)/Makefile.include
